[package]
name = "pcsn"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Wegrzyn"]
description = "PCPU Simulator"
license = "MIT"

[dependencies]
bitflags = "2.3.1"
enumn = "0.1.8"
lazy_static = "1.4.0"
nix = "0.26.2"
